#!/usr/bin/env bash
# This scripts takes in argumenents and prints the dns records
get_subdomain_info(){
	domain="$1"
	subdomain="$2"

	if [ -z "$subdomain" ]; then
		subdomain=("www" "lb-01" "web-01" "web-02")
	else
		subdomain=("${subdomain[@]}")
	fi

	for sub in "${subdomain[@]}"; do
		result=$(dig +short "$sub.$domain")
		if [ -n "$result" ]; then
			record_type=$(dig "$sub.$domain" | awk '/^'"$sub.$domain"'/ {print $4}')
			echo "The subdomain $sub is $record_type record and points to $result"
		fi
	done
}

get_subdomain_info "$1" "$2"
