#!/usr/bin/env bash
# Quering the domain name to get the types of Records

get_subdomain_info() {
	domain="$1"
	subdomain="$2"
	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi
	
	for sub in "${subdomains[@]}"; do
		result=$(dig +short "$sub.$domain")
		if [ -n "$result" ]; then
			record_type=$(dig "$sub.$domain" | awk '/^'"$sub.$domain"'/ {print $4}')
			echo "The subdomain $sub is $record_type record and points to $result"
		fi
	done
}

if [ "$#" == 1 ]
then
	get_subdomain_info "$1"
elif [ "$#" == 2 ]
then
	get_subdomain_info "$1" "$2"
fi
