#!/usr/bin/env bash
# transfering file to local server

file_path=$1
ip=$2
user=$3
ssh_key=$4

if [ "$#" -lt 3 ]; then
	echo "0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
else
	sudo scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$user@$ip":~/
fi
