#!/usr/bin/env bash
# Setting up an Nginx server to operate on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart