#!/usr/bin/env bash
#This script prints etc/passwd using story
while IFS=: read -r username password user_id group_id user_info home_dir cmd_shell
do
	echo "The user $username is part of the $group_id gang,"
	echo "lives in $home_dir and rides $cmd_shell."
	echo "$user_id's place is protected by the passcode $password,"
	echo "more info about the user here: $user_info"
	echo ""
done < /etc/passwd
