#!/usr/bin/env bash

while IFS=: read -r username password user_id group_id user_info home_dir cmd_shell
do
	echo " The user $username is part of the $group_id gang, lives in $home_dir and rides $cmd_shell. $user_id place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
