#!/usr/bin/env bash
#To display HTTP Status code and IP address

if [ ! -f apache-access.log ]
then
	echo "Error: apache-access.log file not found."
	exit 1
fi

awk -F' ' '{ print $1, $9 }' apache-access.log | sort | uniq -c | sort -rn
